# .github/workflows/backend.yml
name: Backend CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        working-directory: backend

      - name: Run Prisma generate
        run: npx prisma generate
        working-directory: backend

      - name: Run build
        run: npm run build
        working-directory: backend

      - name: Run tests
        run: npm test
        working-directory: backend
